spring:
  freemarker:
    suffix: .html

  resources:
    static-locations:
      classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  mvc:
    static-path-pattern: /static/**

server:
  port: 80